### ISSUE TITLE
One error in simple-for-nfv.yaml

### ISSUE THREAD

**Issue by philippemerle** [oasis-open/tosca-community-contributions#107]
**Issue Description**

https://github.com/oasis-open/tosca-community-contributions/blob/master/examples/1.2/simple-for-nfv/simple-for-nfv.yaml provided by @tliron contains one error at https://github.com/oasis-open/tosca-community-contributions/blob/master/examples/1.2/simple-for-nfv/simple-for-nfv.yaml#L19. The `virtual_binding` requirement is assigned two times as illustrated in the following diagram:

![Diagram](https://raw.githubusercontent.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox/master/examples/tosca-community-contributions/diagrams/uml2/examples-1.2-simple-for-nfv-simple-for-nfv-uml2-component-diagram1.png)

But the `virtual_binding` requirement is defined with the default occurrences `[1, 1]` at https://github.com/oasis-open/tosca-community-contributions/blob/master/profiles/org.oasis-open/simple-for-nfv/1.0/nodes.yaml#L211.

**Proposed Resolution**

Split the `VduCp` node template into two `VduCp` node templates as illustrated in the following diagram:

![examples-1 2-simple-for-nfv-simple-for-nfv-uml2-component-diagram1](https://user-images.githubusercontent.com/770247/167785797-89c92e98-d23b-4d85-a2b5-e0adff57e490.png)

**Comment by tliron** [comment]
Thank you, the examples I provided for this repo are out of date and should be updated. Here is the [current version](https://github.com/tliron/puccini/blob/main/examples/tosca/simple-for-nfv.yaml), which is already fixed.

**Comment by philippemerle** [comment]
@tliron My proposed resolution is coded in https://github.com/oasis-open/tosca-community-contributions/pull/108

**Comment by lauwers** [comment]
I think we should remove this example as well as the NFV profile. OASIS never released the NFV profile as a standard (we stopped work after CSC04) and the work was taken over by ETSI.
