### ISSUE TITLE
add a "contains" constraint operator

### ISSUE THREAD

**Issue by lauwers** [oasis-open/tosca-community-contributions#119]
For a project I'm working on, I need additional constraint operators to create more flexible node filters. In my example, nodes have capabilities that expose a list of variables; let's call them tags. Other nodes have requirements for those tags. I need to be able to express the following: "Fulfill my requirement using the node/capability that has a specific tag in its list of exposed tags".
This functionality could be provided using a "contains" constraint operation that can apply to lists, maps, or ranges.

**Comment by tliron** [comment]
I would create separate issues here per constraint you want to add. In this case, `contains`, which I am also in favor. Maybe edit the title?

**Comment by pmjordan** [comment]
If you are going to add 'contains' then it would seem logical to me to add the inverse at the same time, i.e. 'does not contain'

**Comment by tliron** [comment]
As long as we open this up, there are a whole bunch of important, trivial constraints we are missing. Even OpenStack Heat has more.

I propose turning this issue into a general list of possible constraint functions to add.

**Comment by lauwers** [comment]
This function has been added and is documented in https://docs.oasis-open.org/tosca/TOSCA/v2.0/csd05/TOSCA-v2.0-csd05.html#_Toc125468947
