### ISSUE TITLE
Missing version data type

### ISSUE THREAD

**Issue by lauwers** [oasis-open/tosca-community-contributions#128]
Section 5.4.2 in TOSCA-v2.0-wd05-rev03 is missing a description of the `version` data type.

**Comment by tliron** [comment]
Didn't we decide to remove it?

**Comment by lauwers** [comment]
I don't remember making that decisions, but then again my memory is not always perfect :-)
Either way, we need to revisit support for versioning profiles and versioning service templates at some point.

**Comment by lauwers** [comment]
The `version` type is documented in https://docs.oasis-open.org/tosca/TOSCA/v2.0/csd05/TOSCA-v2.0-csd05.html#_Toc125468689
