### ISSUE TITLE
Placing glossary at the document start could make a new reader feel unwelcome

### ISSUE THREAD

**Issue by pmjordan** [oasis-open/tosca-community-contributions#159]
I was trying to read the csd6 as a new reader. The first item I come across is a glossary containg a number of similar, interrelated terms with no context. This may have the effect of making the document more complex than necessary.
I suggest moving the glossary to the end of the overview section.

**Comment by lauwers** [comment]
What I would prefer to do instead is to beef up the **metamodel** section of the document. That section should clearly define the terms that are currently in the glossary. We may no longer need the glossary section if we have a strong metamodel section.

**Comment by pmjordan** [comment]
Fine, I just want to ensure the reader gets a gentle introduction.
