### ISSUE TITLE
Some comments have not been correctly handled when converting to markdown

### ISSUE THREAD

**Issue by pmjordan** [oasis-open/tosca-community-contributions#162]
There are still a number of places where comments have been either converted to text or omitted from the preview. See for example lines 285 - 300 where 'Mike Rehder' appears in the text but comment 95 from Calin does not appear in the preview.

**Comment by lauwers** [comment]
Comments are not supposed to show up in the rendered document, only in the markdown text itself. If comments show up (such as the Mike Rehder comment you're referencing) that is a big in the document.

**Comment by pmjordan** [comment]
OK. I'll see if I can find any other places where comments have leaked through to text. However it does seem that some comments are rendered deliberately e.g. lines 670-674

**Comment by pmjordan** [comment]
I found one more comment breaking thirugh at Lines 1969 - 1972 'MUSTFIX'
and several occurances each of
TODO
TBD
!!!

also dollar signs are cauing a problem in lines 7936 - 7937

**Comment by pmjordan** [comment]
This issue was addressed by https://github.com/oasis-tcs/tosca-specs/issues/61 so closing
