### ISSUE TITLE
CSD06: Section 6.4.1: Markdown table not correctly rendered in HTML

### ISSUE THREAD

**Issue by koppor** [oasis-open/tosca-community-contributions#170]
https://docs.oasis-open.org/tosca/TOSCA/v2.0/csd06/TOSCA-v2.0-csd06.html#641-common-keynames-in-type-definitions

![image](https://github.com/oasis-open/tosca-community-contributions/assets/1366654/2a5a4f1d-7e03-4b5d-9217-356180794ca8)

**Comment by lauwers** [comment]
This renders correctly on github.com:

https://github.com/lauwers/tosca-specs/blob/published/tosca_2_0/TOSCA-v2.0-csd06.md#641-common-keynames-in-type-definitions

Unlike other tables in the document, this table does not have a blank line immediately preceding it. I added a blank line in the CSD07 draft in the hopes that this will fix the problem.
