### ISSUE TITLE
TOSCA 2.0: Clarify or replace "occurrences" keyword on capability type definitions and declarations.

### ISSUE THREAD

**Issue by aszs** [oasis-open/tosca-community-contributions#54]
What to do with "occurrences" keyword in requirements and capabilities, at both the node type and node template levels.

(cf TOSCA TC TODO Item 1)

**Comment by lauwers** [comment]
Support for `occurrences` in capabilities has been removed. Neither the capability type definition in https://docs.oasis-open.org/tosca/TOSCA/v2.0/csd05/TOSCA-v2.0-csd05.html#_Toc125468556 or the capability definition in https://docs.oasis-open.org/tosca/TOSCA/v2.0/csd05/TOSCA-v2.0-csd05.html#_Toc125468561 allow the `occurrences` keyword.
