### ISSUE TITLE
Graph traversal language for get_property and get_attribute

### ISSUE THREAD

**Issue by aszs** [oasis-open/tosca-community-contributions#66]

**Comment by philippemerle** [comment]
Is this issue related to issue https://github.com/oasis-open/tosca-community-contributions/issues/69?

**Comment by lauwers** [comment]
General-purpose TOSCA Path syntax has been introduced for this purpose in https://docs.oasis-open.org/tosca/TOSCA/v2.0/csd05/TOSCA-v2.0-csd05.html#_Toc125468587
