### ISSUE TITLE
General purpose expression language for TOSCA? See: Gremlin

### ISSUE THREAD

**Issue by aszs** [oasis-open/tosca-community-contributions#69]

**Comment by philippemerle** [comment]
Why not but the general purpose expression language of TOSCA must be totally defined inside the TOSCA specification (huge work) or based on an existing *standardized* expression language (which one?).

**Comment by lauwers** [comment]
Support for custom functions defined in https://docs.oasis-open.org/tosca/TOSCA/v2.0/csd05/TOSCA-v2.0-csd05.html#_Toc125468802 combined with the extended TOSCA Path syntax defined in https://docs.oasis-open.org/tosca/TOSCA/v2.0/csd05/TOSCA-v2.0-csd05.html#_Toc125468897 should address this issue for now.
