### ISSUE TITLE
Can we get rid of policy triggers?

### ISSUE THREAD

**Issue by aszs** [oasis-open/tosca-community-contributions#75]

**Comment by philippemerle** [comment]
Policy triggers are the current way in TOSCA to react to (internal/external) events.
Only removing them will remove the ability to implement reactive topologies.
Or will another proposal replace policy triggers?

**Comment by lauwers** [comment]
Yes, policy triggers are the mechanism for specifying the semantics of “imperative” policies (i.e. event/condition/action policies). We should have a discussion instead about how to improve on the syntax for imperative policies as well as about how to add support for declarative policies (that use a “context/capability/constraint” pattern).

**Comment by philippemerle** [comment]
Could an example of a declarative policy be illustrated?

**Comment by lauwers** [comment]
There doesn't seem to be any support for removing policy triggers. We should instead focus on cleaning up the policy syntax. We should also focus on extending our current syntax with `declarative policies` as discussed in Issue https://github.com/oasis-open/tosca-community-contributions/issues/141
