### ISSUE TITLE
Are we removing "json" and "yaml" built-in types?

### ISSUE THREAD

**Issue by aszs** [oasis-open/tosca-community-contributions#77]

**Comment by philippemerle** [comment]
I don't remember that "json" or "yaml" are built-in types in TOSCA, at least json is a data type, i.e. tosca.datatypes.json.
As TOSCA 2.0 does not define any types, it seems that this issue has no sense for TOSCA 2.0.

**Comment by lauwers** [comment]
Philippe is correct. There are no built-in TOSCA types for JSON or XML, only for strings. Closing this issue.
