### ISSUE TITLE
Support more complex constraint logic, inspired by OpenAPI

### ISSUE THREAD

**Issue by aszs** [oasis-open/tosca-community-contributions#80]

**Comment by philippemerle** [comment]
Could you illustrate what complex constraint logic could be expressed with OpenAPI and can not be expressed with TOSCA?

**Comment by lauwers** [comment]
This issue has been addressed by turning constraint clauses into Boolean expressions as documented in https://docs.oasis-open.org/tosca/TOSCA/v2.0/csd05/TOSCA-v2.0-csd05.html#_Toc125468755
