### ISSUE TITLE
Can/should requirements be refined?

### ISSUE THREAD

**Issue by aszs** [oasis-open/tosca-community-contributions#85]

**Comment by philippemerle** [comment]
yes the refinement of requirements should be allowed, and refinement rules shall be precisely defined.

**Comment by lauwers** [comment]
Closing this issue, since requirement refinements are already fully supported (refinement rules for requirement definitions are stated in Section 5.3.5.5.3 of the TOSCA Version 2 specification). If specific rules need to be added or changed, then we should open a separate issue.
